
spring.config.import=classpath:jcart-core.properties
spring.profiles.default=dev


################### Web Configuration ##########################

#spring.thymeleaf.mode=LEGACYHTML5
#spring.thymeleaf.cache=false

server.port=8443
server.ssl.key-store=classpath:jcartsitekeystore.p12
server.ssl.key-store-password=jcartsite
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=jcartsitetomcat
