package com.sivalabs.jcart;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import javax.sql.DataSource;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Baseline of the schema generated by Hibernate (ddl-auto=update) and of the
 * seed data loaded from data.sql. Any change here after the upgrade means the
 * schema/seed handling changed (Hibernate 6 naming, H2 2.x reserved words,
 * data.sql ordering, etc.).
 */
public class SeedDataTest extends AbstractCoreIntegrationTest
{
	@Autowired DataSource dataSource;

	private JdbcTemplate jdbc()
	{
		return new JdbcTemplate(dataSource);
	}

	@Test
	public void databaseCatalogIsJcart() throws Exception
	{
		assertEquals("jcart", dataSource.getConnection().getCatalog().toLowerCase());
	}

	@Test
	public void seedRowCounts()
	{
		assertEquals(9, count("permissions"));
		assertEquals(4, count("roles"));
		assertEquals(5, count("users"));
		assertEquals(3, count("categories"));
		assertEquals(25, count("products"));
		assertEquals(2, count("customers"));
		assertEquals(1, count("addresses"));
		assertEquals(1, count("payments"));
		assertEquals(1, count("orders"));
		assertEquals(1, count("order_items"));
		assertEquals(17, count("role_permission"));
		assertEquals(6, count("user_role"));
	}

	@Test
	public void expectedTablesAndColumnsExist()
	{
		// Column names come from @Column(name=...) / default naming strategy.
		// Hibernate 6 default naming and H2 2.x keyword handling must keep these.
		assertEquals(1, jdbc().queryForObject("select count(*) from orders where order_number = '1447737431927'", Integer.class).intValue());
		assertEquals(1, jdbc().queryForObject("select count(*) from categories where disp_order = 1", Integer.class).intValue());
		assertEquals(25, jdbc().queryForObject("select count(*) from products where cat_id is not null and created_on is not null", Integer.class).intValue());
		assertEquals(1, jdbc().queryForObject("select count(*) from orders where cust_id = 1 and billing_addr_id = 1 and delivery_addr_id = 1 and payment_id = 1", Integer.class).intValue());
		assertEquals(1, jdbc().queryForObject("select count(*) from payments where cc_number = '1111111111111111'", Integer.class).intValue());
		assertEquals(1, jdbc().queryForObject("select count(*) from addresses where address_line1 = 'Hitech City' and zip_code = '500088'", Integer.class).intValue());
	}

	@Test
	public void seedPasswordsAreStoredAsBCryptHashes()
	{
		// Plaintext/hash matching is verified in the admin/site modules where
		// Spring Security is on the classpath.
		assertEquals(5, jdbc().queryForObject("select count(*) from users where password like '$2a$10$%'", Integer.class).intValue());
		assertEquals(2, jdbc().queryForObject("select count(*) from customers where password like '$2a$10$%'", Integer.class).intValue());
		assertTrue(userPassword("superadmin@gmail.com").length() == 60);
	}

	private int count(String table)
	{
		return jdbc().queryForObject("select count(*) from " + table, Integer.class);
	}

	private String userPassword(String email)
	{
		return jdbc().queryForObject("select password from users where email = ?", String.class, email);
	}
}
